import assert from 'node:assert/strict'
import test from 'node:test'
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs'

import {
  CHROME_BUILD_TARGET,
  MINIMUM_CHROME_VERSION,
  chromeSupportPolicy
} from '../src/extension/chrome-support.js'
import { createIndexHtml } from '../src/index-html.js'
import { createExtensionManifest } from '../src/extension/manifest.js'

test('extension HTML loads the Vite-built React entry', async () => {
  assert.ok(existsSync('package.json'), 'package.json should define the Vite build')
  assert.ok(existsSync('scripts/build-extension.ts'), 'scripts/build-extension.ts should generate package files and build extension entries without shared runtime chunks')
  assert.ok(existsSync('scripts/check-tailwind-diagnostics.ts'), 'the Tailwind diagnostics client should be strict TypeScript')
  assert.ok(existsSync('scripts/check-commit-references.ts'), 'commit reference checks should guard immutable commit messages')
  assert.ok(existsSync('scripts/chrome-support.ts'), 'scripts/chrome-support.ts should maintain the rolling Chrome floor')
  assert.ok(existsSync('scripts/react-compiler-check.ts'), 'the React Compiler coverage gate should be strict TypeScript')
  assert.ok(existsSync('scripts/serve.ts'), 'the local fixture server should be strict TypeScript')
  assert.ok(existsSync('scripts/watch-build.ts'), 'scripts/watch-build.ts should drive local rebuilds without watching dist output')
  assert.ok(existsSync('tsconfig.node.json'), 'Node-executed TypeScript should have a NodeNext compiler boundary')
  assert.deepEqual(
    readdirSync('scripts').filter((file) => file.endsWith('.mjs')),
    [],
    'maintained Node scripts should use TypeScript'
  )
  assert.ok(existsSync('src/app.tsx'), 'src/app.tsx should be the React entry source')
  assert.ok(existsSync('src/extension/background.ts'), 'src/extension/background.ts should be the service worker source')
  assert.ok(existsSync('src/extension/manifest.ts'), 'src/extension/manifest.ts should be the manifest source')
  assert.ok(existsSync('src/index-html.tsx'), 'src/index-html.tsx should be the dashboard page source')
  assert.ok(existsSync('src/index-html.template.html'), 'src/index-html.template.html should define the static dashboard page wrapper')
  assert.ok(existsSync('src/index-html.template.d.html.ts'), 'the HTML template should expose its string type through an arbitrary-extension declaration')
  assert.ok(existsSync('components.json'), 'components.json should define the shadcn project setup')
  assert.ok(existsSync('.dependency-cruiser.cjs'), 'dependency-cruiser should define repository architecture rules')
  assert.ok(
    existsSync('.dependency-cruiser-known-violations.json'),
    'dependency-cruiser should baseline existing graph debt'
  )
  assert.ok(existsSync('chrome-support.json'), 'chrome-support.json should be the tracked browser-support policy')

  const pkg = JSON.parse(readFileSync('package.json', 'utf8'))
  const tsconfig = JSON.parse(readFileSync('tsconfig.json', 'utf8'))
  const nodeTsconfig = JSON.parse(readFileSync('tsconfig.node.json', 'utf8'))
  const testTsconfig = JSON.parse(readFileSync('tsconfig.test.json', 'utf8'))
  const shadcnConfig = JSON.parse(readFileSync('components.json', 'utf8'))
  assert.equal(readFileSync('.node-version', 'utf8').trim(), '26.5.0')
  assert.match(pkg.packageManager, /^pnpm@/)
  assert.equal(pkg.scripts?.['setup:hooks'], 'git config core.hooksPath .githooks')
  assert.equal(
    pkg.scripts?.['commit-references:check'],
    'tsx scripts/check-commit-references.ts'
  )
  assert.equal(pkg.scripts?.dev, 'node scripts/watch-build.ts')
  assert.equal(pkg.scripts?.serve, 'node scripts/serve.ts')
  assert.equal(pkg.scripts?.build, 'node --experimental-import-text --import tsx scripts/build-extension.ts')
  assert.equal(pkg.scripts?.['build:debug'], 'node --experimental-import-text --import tsx scripts/build-extension.ts --sourcemap')
  assert.match(pkg.scripts?.typecheck, /tsconfig\.node\.json/)
  assert.match(pkg.scripts?.test, /--experimental-import-text/)
  assert.equal(pkg.scripts?.lint, 'eslint . --max-warnings=0')
  assert.equal(
    pkg.scripts?.['deps:architecture'],
    'depcruise --config .dependency-cruiser.cjs --ignore-known .dependency-cruiser-known-violations.json src'
  )
  assert.equal(pkg.scripts?.['deps:nolyfill'], 'pnpm dlx nolyfill --pm pnpm')
  assert.match(pkg.scripts?.['test:browser'], /playwright test/)
  assert.match(pkg.scripts?.['test:browser'], /dashboard-smoke\.spec\.ts/)
  assert.doesNotMatch(pkg.scripts?.['test:browser'], /RUN_BROWSER_SMOKE/)
  assert.match(pkg.scripts?.['test:browser:layout'], /dashboard-layout\.spec\.ts/)
  assert.equal(pkg.scripts?.['verify:bundle'], 'git diff --exit-code -- extension/dist')
  assert.equal(pkg.scripts?.['verify:compiler'], 'node scripts/react-compiler-check.ts')
  assert.equal(pkg.scripts?.['lint:tailwind'], 'node scripts/check-tailwind-diagnostics.ts')
  assert.equal(
    pkg.scripts?.['verify:quick'],
    'pnpm run "/^(typecheck|lint|lint:tailwind|deps:architecture|react-doctor|verify:compiler)$/"'
  )
  assert.match(pkg.scripts?.verify, /pnpm lint:tailwind/)
  assert.match(pkg.scripts?.verify, /^pnpm chrome-support:check &&/)
  assert.match(pkg.scripts?.verify, /pnpm lint/)
  assert.match(pkg.scripts?.verify, /pnpm deps:architecture/)
  assert.match(pkg.scripts?.verify, /pnpm verify:bundle/)
  assert.match(pkg.scripts?.['verify:browser'], /pnpm test:browser/)
  assert.ok(pkg.dependencies?.react)
  assert.ok(pkg.dependencies?.['react-dom'])
  assert.ok(pkg.dependencies?.['@base-ui/react'])
  assert.equal(pkg.dependencies?.['class-variance-authority'], undefined)
  assert.ok(pkg.dependencies?.foxact)
  assert.ok(pkg.devDependencies?.['@types/chrome'])
  assert.match(pkg.devDependencies?.['@types/node'], /^\^26\./)
  assert.ok(pkg.devDependencies?.['@rolldown/plugin-babel'])
  assert.ok(pkg.devDependencies?.['@tailwindcss/vite'])
  assert.ok(pkg.devDependencies?.['@iconify-json/ooui'])
  assert.ok(pkg.devDependencies?.['babel-plugin-react-compiler'])
  assert.ok(pkg.devDependencies?.['dependency-cruiser'])
  assert.ok(pkg.devDependencies?.['fast-check'])
  assert.ok(pkg.devDependencies?.tailwindcss)
  assert.ok(pkg.devDependencies?.vite)
  assert.ok(pkg.devDependencies?.shadcn)
  assert.ok(pkg.devDependencies?.['@sinonjs/fake-timers'])
  assert.equal(pkg.devDependencies?.['type-fest'], undefined)
  assert.ok(tsconfig.compilerOptions?.types?.includes('chrome'))
  assert.equal(tsconfig.compilerOptions?.allowArbitraryExtensions, true)
  assert.equal(tsconfig.compilerOptions?.allowUnreachableCode, false)
  assert.equal(tsconfig.compilerOptions?.noFallthroughCasesInSwitch, true)
  assert.equal(tsconfig.compilerOptions?.noImplicitReturns, true)
  assert.equal(tsconfig.compilerOptions?.noUncheckedIndexedAccess, true)
  assert.equal(tsconfig.compilerOptions?.noUncheckedSideEffectImports, true)
  assert.equal(tsconfig.compilerOptions?.exactOptionalPropertyTypes, true)
  assert.equal(tsconfig.compilerOptions?.strict, true)
  assert.equal(nodeTsconfig.extends, './tsconfig.json')
  assert.equal(nodeTsconfig.compilerOptions?.module, 'NodeNext')
  assert.equal(nodeTsconfig.compilerOptions?.moduleResolution, 'NodeNext')
  assert.deepEqual(nodeTsconfig.compilerOptions?.types, ['node'])
  assert.deepEqual(nodeTsconfig.compilerOptions?.paths, {})
  assert.ok(nodeTsconfig.files?.includes('scripts/check-tailwind-diagnostics.ts'))
  assert.ok(nodeTsconfig.files?.includes('scripts/react-compiler-check.ts'))
  assert.ok(nodeTsconfig.files?.includes('scripts/serve.ts'))
  assert.ok(nodeTsconfig.files?.includes('scripts/watch-build.ts'))
  assert.equal(testTsconfig.extends, './tsconfig.json')
  assert.equal(testTsconfig.compilerOptions, undefined)
  assert.deepEqual(tsconfig.compilerOptions?.paths?.['@/*'], ['./src/*'])
  assert.equal(CHROME_BUILD_TARGET, `chrome${chromeSupportPolicy.minimumMajor}`)
  assert.equal(MINIMUM_CHROME_VERSION, String(chromeSupportPolicy.minimumMajor))
  assert.equal(shadcnConfig.style, 'base-nova')
  assert.equal(shadcnConfig.rsc, false)
  assert.equal(shadcnConfig.tsx, true)
  assert.equal(shadcnConfig.tailwind?.css, 'src/styles/app.css')
  assert.equal(shadcnConfig.tailwind?.config, '')
  assert.equal(shadcnConfig.tailwind?.cssVariables, true)
  assert.equal(shadcnConfig.aliases?.ui, '@/components/ui')
  assert.equal(shadcnConfig.aliases?.components, '@/components')
  assert.equal(shadcnConfig.aliases?.utils, '@/lib/utils')
  assert.equal(shadcnConfig.aliases?.lib, '@/lib')

  const indexHtml = readFileSync('extension/index.html', 'utf8')
  const indexHtmlTemplate = readFileSync('src/index-html.template.html', 'utf8')
  assert.equal(indexHtmlTemplate.split('<!-- TAB_OUT_PRERENDERED_APP -->').length, 2)
  assert.equal(indexHtml, await createIndexHtml())
  assert.doesNotMatch(indexHtml, /TAB_OUT_PRERENDERED_APP/)
  const appRootStart = indexHtml.indexOf('<div id="appRoot">') + '<div id="appRoot">'.length
  const appRootEnd = indexHtml.indexOf('</div>\n    <!-- TAB_OUT_APP_ROOT_END -->', appRootStart)
  assert.ok(appRootStart >= '<div id="appRoot">'.length)
  assert.ok(appRootEnd > appRootStart)
  const appRootContent = indexHtml.slice(appRootStart, appRootEnd)
  assert.equal(appRootContent.trim(), appRootContent)
  assert.match(appRootContent, /^<div data-tabout="dashboard-shell"/)
  assert.doesNotMatch(appRootContent, /filterFocusBootShell/)
  assert.match(indexHtml, /rel="modulepreload" href="dist\/app\.js"/)
  assert.match(indexHtml, /href="dist\/assets\/app\.css"/)
  assert.match(indexHtml, /src="dist\/filter-focus-boot\.js"/)
  assert.doesNotMatch(indexHtml, /config\.local\.js/)
  assert.match(indexHtml, /src="dist\/app\.js"/)
  assert.doesNotMatch(indexHtml, /src="app\.js"/)

  const manifest = JSON.parse(readFileSync('extension/manifest.json', 'utf8'))
  assert.deepEqual(manifest, createExtensionManifest({ version: pkg.version }))
  assert.equal(manifest.background?.service_worker, 'dist/background.js')
  assert.equal(manifest.version, pkg.version)
  assert.equal(manifest.incognito, 'not_allowed')
  assert.equal(manifest.minimum_chrome_version, MINIMUM_CHROME_VERSION)

  const viteConfig = readFileSync('vite.config.ts', 'utf8')
  const buildScript = readFileSync('scripts/build-extension.ts', 'utf8')
  const manifestSource = readFileSync('src/extension/manifest.ts', 'utf8')
  const indexHtmlSource = readFileSync('src/index-html.tsx', 'utf8')
  const serveScript = readFileSync('scripts/serve.ts', 'utf8')
  const watchScript = readFileSync('scripts/watch-build.ts', 'utf8')
  assert.match(indexHtmlSource, /import \{ prerender \} from 'react-dom\/static'/)
  assert.match(indexHtmlSource, /import \{ AppRoot \} from '\.\/components\/App\.js'/)
  assert.match(indexHtmlSource, /import indexHtmlTemplate from '\.\/index-html\.template\.html' with \{ type: 'text' \}/)
  assert.match(indexHtmlSource, /await prerender\(<AppRoot \/>\)/)
  assert.match(manifestSource, /chrome\.runtime\.ManifestV3/)
  assert.match(manifestSource, /minimum_chrome_version: MINIMUM_CHROME_VERSION/)
  assert.match(manifestSource, /permissions: \['tabs', 'tabGroups', 'bookmarks', 'history', 'sessions', 'storage', 'alarms', 'favicon', 'system\.display', 'nativeMessaging'\]/)
  assert.match(viteConfig, /reactCompilerPreset/)
  assert.match(viteConfig, /@rolldown\/plugin-babel/)
  assert.match(viteConfig, /@tailwindcss\/vite/)
  assert.match(viteConfig, /TAB_OUT_BUILD_ENTRY/)
  assert.match(viteConfig, /target: CHROME_BUILD_TARGET/)
  assert.match(viteConfig, /find: \/\^tldts\$\//)
  assert.match(viteConfig, /tldts\/dist\/index\.esm\.min\.js/)
  assert.ok(existsSync('node_modules/tldts/dist/index.esm.min.js'))
  assert.match(viteConfig, /buildEntry === 'background' \? \{ codeSplitting: false \} : \{\}/)
  assert.match(viteConfig, /const repoRoot = import\.meta\.dirname/)
  assert.match(viteConfig, /\{ find: '@', replacement: resolve\(repoRoot, 'src'\) \}/)
  assert.match(viteConfig, /src\/extension\/background\.ts/)
  assert.match(buildScript, /createExtensionManifest/)
  assert.match(buildScript, /createIndexHtml/)
  assert.match(buildScript, /extension\/manifest\.json/)
  assert.match(buildScript, /extension\/index\.html/)
  assert.match(buildScript, /ChildProcess\.make\('pnpm'/)
  assert.match(buildScript, /runBuild\('app', viteArgs\)/)
  assert.match(buildScript, /runBuild\('background', viteArgs\)/)
  assert.match(buildScript, /Effect\.provide\(NodeServices\.layer\)/)
  assert.match(buildScript, /NodeRuntime\.runMain/)
  assert.match(watchScript, /from 'node:fs'/)
  assert.match(watchScript, /watch\(path, \{ recursive \}/)
  assert.match(watchScript, /ChildProcess\.make\('pnpm'/)
  assert.match(watchScript, /Effect\.provide\(NodeServices\.layer\)/)
  assert.match(watchScript, /NodeRuntime\.runMain/)
  assert.match(serveScript, /NodeHttpServer\.make\(createServer/)
  assert.match(serveScript, /HttpServerResponse\.file/)
  assert.match(serveScript, /Effect\.provide\(NodeHttpServer\.layerHttpServices\)/)
  assert.match(serveScript, /NodeRuntime\.runMain/)
  assert.match(watchScript, /scripts.*build-extension\.ts/)
  assert.doesNotMatch(watchScript, /extension\/dist/)
  assert.doesNotMatch(watchScript, /POLL_MS|snapshotFiles/)

  const appSource = readFileSync('src/app.tsx', 'utf8')
  const appStylesheet = readFileSync('src/styles/app.css', 'utf8')
  const appComponentSource = readFileSync('src/components/App.tsx', 'utf8')
  const dashboardInteractionContextSource = readFileSync('src/components/DashboardInteractionContext.tsx', 'utf8')
  const useHoverMatchSource = readFileSync('src/hooks/useHoverMatch.ts', 'utf8')
  const useUrlPreviewSource = readFileSync('src/hooks/useUrlPreview.ts', 'utf8')
  const baseStylesheet = readFileSync('extension/base.css', 'utf8')
  const domainCardSource = readFileSync('src/components/DomainCard.tsx', 'utf8')
  const domainCardContextSource = readFileSync('src/components/DomainCardContext.tsx', 'utf8')
  const flatSectionSource = readFileSync('src/components/FlatSection.tsx', 'utf8')
  const pageChipSource = readFileSync('src/components/PageChip.tsx', 'utf8')
  const pageChipOverflowSource = readFileSync('src/components/PageChipOverflow.tsx', 'utf8')
  const pageTargetSource = readFileSync('src/extension/page-target.ts', 'utf8')
  const tabFocusSource = readFileSync('src/extension/tab-focus.ts', 'utf8')
  const pathgroupSectionSource = readFileSync('src/components/PathgroupSection.tsx', 'utf8')
  const subdomainSectionSource = readFileSync('src/components/SubdomainSection.tsx', 'utf8')
  const tabHistoryPanelSource = readFileSync('src/components/TabHistoryPanel.tsx', 'utf8')
  const tabHistorySource = readFileSync('src/extension/tab-history.ts', 'utf8')
  const tabHistoryServiceSource = readFileSync('src/extension/background/tab-history-service.ts', 'utf8')
  const headerBarSource = readFileSync('src/components/HeaderBar.tsx', 'utf8')
  const historyRangeSelectSource = readFileSync('src/components/HistoryRangeSelect.tsx', 'utf8')
  const workingSetClientSource = readFileSync('src/extension/working-set-client.ts', 'utf8')
  const toastSource = readFileSync('src/components/Toast.tsx', 'utf8')
  const mountToastSource = readFileSync('src/components/mountToast.tsx', 'utf8')
  const toastClientSource = readFileSync('src/extension/toast.ts', 'utf8')
  const contextMenuSource = readFileSync('src/components/ui/context-menu.tsx', 'utf8')
  const contextMenuRegistrySource = readFileSync('src/components/ui/context-menu-registry.ts', 'utf8')
  const menuStylesSource = readFileSync('src/components/ui/menu-styles.ts', 'utf8')
  const tabsSource = readFileSync('src/components/ui/tabs.tsx', 'utf8')
  const uiFiles = readdirSync('src/components/ui').sort()
  const selectSource = readFileSync('src/components/ui/select.tsx', 'utf8')
  const tooltipSource = readFileSync('src/components/ui/tooltip.tsx', 'utf8')
  const utilsSource = readFileSync('src/lib/utils.ts', 'utf8')
  const sharedTypesSource = readFileSync('src/extension/types.d.ts', 'utf8')
  assert.match(pageTargetSource, /export function pageTargetMatchUrls/)
  assert.match(pageTargetSource, /export function pageTargetMatchesHover/)
  assert.match(tabFocusSource, /export const focusExistingTabTargetEffect = Effect\.fn/)
  assert.match(tabFocusSource, /getAppRuntime\(\)\.runPromise\(focusExistingTabTargetEffect/)
  assert.match(readFileSync('src/extension/browser-tabs-gateway.ts', 'utf8'), /sendMessage\(extensionId, \{ action: 'unsuspend', tabId \}\)/)
  assert.match(tabFocusSource, /updateProperties\.url = targetEffective/)
  assert.match(tabHistorySource, /focusExistingTabTarget/)
  assert.match(workingSetClientSource, /focusExistingTabTarget/)
  assert.match(tabHistoryServiceSource, /focusExistingTabTarget/)
  assert.match(tabHistoryServiceSource, /const url = unwrapSuspenderUrl\(rawUrl\)/)
  // The chip + history-row <div role="button"> surfaces cancel native text
  // selection on mousedown for the Shift move-to-new-window and ⌘/⌃
  // move-to-current-window gestures (a plain click still drag-selects). Guard the wiring so the selection leak can't regress.
  assert.match(pageChipSource, /shouldSuppressSelectionForGesture/)
  assert.match(pageChipSource, /onMouseDown:\s*onChipPointerDown/)
  assert.match(tabHistoryPanelSource, /shouldSuppressSelectionForGesture/)
  assert.match(tabHistoryPanelSource, /onMouseDown=\{!expanded && canActivateEntry \? onEntryMouseDown : undefined\}/)
  assert.match(sharedTypesSource, /interface TabHistoryEntry[\s\S]*rawUrl: string/)
  assert.match(appSource, /styles\/app\.css/)
  assert.doesNotMatch(
    [appComponentSource, domainCardSource, pageChipSource, tabHistoryPanelSource].join('\n'),
    /text-\[11px\]/
  )
  assert.match(`${appComponentSource}\n${toastSource}\n${mountToastSource}`, /react-dom\/client/)
  assert.doesNotMatch(appSource, /mountToast/)
  assert.doesNotMatch(toastClientSource, /@base-ui\/react\/toast/)
  assert.match(toastClientSource, /import\('\.\.\/components\/mountToast'\)/)
  assert.match(contextMenuRegistrySource, /activeContextMenuId/)
  assert.match(contextMenuRegistrySource, /export function isContextMenuOpen\(\)/)
  assert.match(contextMenuSource, /import \{ clearActiveContextMenu, setActiveContextMenu \} from '\.\/context-menu-registry'/)
  assert.match(contextMenuSource, /import \{ menuItemClassName, menuPopupClassName \} from '\.\/menu-styles'/)
  assert.match(contextMenuSource, /onOpenChange=\{handleOpenChange\}/)
  assert.match(contextMenuSource, /ContextMenuPrimitive\.Backdrop/)
  assert.match(contextMenuSource, /data-slot="context-menu-backdrop"/)
  assert.match(contextMenuSource, /fixed inset-0 z-60/)
  assert.match(contextMenuSource, /className="isolate z-70"/)
  assert.match(contextMenuSource, /onPointerDown=\{stopBackdropEvent\}/)
  assert.match(contextMenuSource, /onClick=\{stopBackdropEvent\}/)
  assert.match(contextMenuSource, /menuPopupClassName/)
  assert.match(contextMenuSource, /menuItemClassName/)
  assert.match(menuStylesSource, /relative isolate z-70 min-w-40/)
  assert.match(menuStylesSource, /rounded-\[15px\] bg-popover p-1/)
  assert.match(menuStylesSource, /min-h-6 min-w-36/)
  assert.match(menuStylesSource, /gap-1\.5 rounded-lg px-2 py-1 text-\[13px\]/)
  assert.match(headerBarSource, /<input[\s\S]*data-slot="input"/)
  assert.match(tabsSource, /@base-ui\/react\/tabs/)
  assert.match(tabsSource, /data-slot="tabs"/)
  assert.match(tabsSource, /data-slot="tabs-list"/)
  assert.match(tabsSource, /data-slot="tabs-trigger"/)
  assert.match(tabsSource, /variant === 'line'/)
  assert.doesNotMatch(tabsSource, /class-variance-authority|tabsListVariants/)
  assert.doesNotMatch(tabsSource, /TabsIndicator/)
  assert.match(tooltipSource, /@base-ui\/react\/tooltip/)
  assert.match(tooltipSource, /import \{ isContextMenuOpen \} from '\.\/context-menu-registry'/)
  assert.match(tooltipSource, /data-slot="tooltip-content"/)
  assert.match(tooltipSource, /TOOLTIP_INITIAL_REST_DELAY_MS = 500/)
  assert.match(tooltipSource, /TOOLTIP_ADJACENT_REST_DELAY_MS = 180/)
  assert.match(tooltipSource, /TOOLTIP_ADJACENT_REST_WINDOW_MS = 700/)
  assert.match(tooltipSource, /TOOLTIP_HOVERABLE_CLOSE_DELAY_MS = 160/)
  assert.match(tooltipSource, /TOOLTIP_HOVER_WATCH_INTERVAL_MS = 80/)
  assert.doesNotMatch(tooltipSource, /TooltipPrimitive\.Provider/)
  assert.match(tooltipSource, /disableHoverablePopup = false/)
  assert.match(tooltipSource, /trackCursorAxis = 'none'/)
  assert.match(tooltipSource, /tooltipOpen/)
  assert.match(tooltipSource, /open=\{tooltipOpen\}/)
  assert.match(tooltipSource, /setTooltipOpen\(false\)/)
  assert.match(tooltipSource, /useAbortableEffect\(\(signal\) => \{[\s\S]*window\.addEventListener\('scroll', handleScroll, \{ capture: true, passive: true, signal \}\)/)
  assert.match(tooltipSource, /window\.addEventListener\('blur', handleWindowBlur, \{ signal \}\)/)
  assert.doesNotMatch(tooltipSource, /window\.removeEventListener\('scroll', handleScroll/)
  assert.doesNotMatch(tooltipSource, /window\.removeEventListener\('blur', handleWindowBlur/)
  assert.match(tooltipSource, /foxact\/merge-refs/)
  assert.match(tooltipSource, /foxact\/use-abortable-effect/)
  assert.match(tooltipSource, /foxact\/use-retimer/)
  assert.doesNotMatch(tooltipSource, /foxact\/use-page-visibility/)
  assert.doesNotMatch(tooltipSource, /usePageVisibility/)
  assert.match(tooltipSource, /const handleVisibilityChange = \(\) => \{[\s\S]*document\.visibilityState !== 'visible'[\s\S]*closeTooltip\(\)/)
  assert.match(tooltipSource, /document\.addEventListener\('visibilitychange', handleVisibilityChange, \{ signal \}\)/)
  assert.doesNotMatch(tooltipSource, /document\.removeEventListener\('visibilitychange', handleVisibilityChange/)
  assert.match(tooltipSource, /latestPointerPointRef/)
  assert.match(tooltipSource, /retimeHoverOpen/)
  assert.match(tooltipSource, /retimeHoverClose/)
  assert.match(tooltipSource, /hoverCloseScheduledRef/)
  assert.match(
    tooltipSource,
    /onOpenChange\?: \(\(open: boolean\) => void\) \| undefined/
  )
  assert.match(tooltipSource, /onOpenChange\?\.\(true\)/)
  assert.match(tooltipSource, /onOpenChange\?\.\(false\)/)
  assert.match(tooltipSource, /pointerFocusedRef/)
  assert.match(tooltipSource, /popupPointerInsideRef/)
  assert.match(tooltipSource, /shouldUseAdjacentTooltipDelay/)
  assert.match(tooltipSource, /onPointerEnter=\{handleContentPointerEnter\}/)
  assert.match(tooltipSource, /onPointerLeave=\{handleContentPointerLeave\}/)
  assert.match(tooltipSource, /onMouseEnter=\{handleContentMouseEnter\}/)
  assert.match(tooltipSource, /onMouseLeave=\{handleContentMouseLeave\}/)
  assert.match(tooltipSource, /pointerInsideRef\.current \|\| popupPointerInsideRef\.current/)
  assert.match(tooltipSource, /setTooltipWheelPassthrough/)
  assert.match(tooltipSource, /startTooltipWheelForwarding/)
  assert.match(tooltipSource, /handleTooltipWheelForward/)
  assert.match(tooltipSource, /tooltipWheelForwardRefresh\?\.\(\)/)
  assert.match(tooltipSource, /TOOLTIP_WHEEL_TARGET_RELEASE_DELAY_MS = 320/)
  assert.match(tooltipSource, /data-tooltip-wheel-closing/)
  assert.match(tooltipSource, /window\.addEventListener\('wheel', handleTooltipWheelForward/)
  assert.match(tooltipSource, /target\.style\.setProperty\('pointer-events', 'none'\)/)
  assert.match(tooltipSource, /TOOLTIP_WHEEL_CLOSE_REOPEN_BLOCK_MS = 900/)
  assert.match(tooltipSource, /if \(!hoverCloseScheduledRef\.current\) \{[\s\S]*scheduleHoverClose\(\)/)
  assert.match(tooltipSource, /if \(isContextMenuOpen\(\)\) \{[\s\S]*clearHoverCloseTimer\(\)[\s\S]*return[\s\S]*\}/)
  assert.match(tooltipSource, /matches\(':hover'\)/)
  assert.match(tooltipSource, /window\.addEventListener\('pointermove', handlePointerMove, \{ capture: true, signal \}\)/)
  assert.doesNotMatch(tooltipSource, /document\.addEventListener\('pointermove'/)
  assert.doesNotMatch(tooltipSource, /addEventListener\('mousemove'/)
  assert.match(tooltipSource, /!pointerFocusedRef\.current[\s\S]*triggerElement\?\.contains\(activeElement\)/)
  assert.match(tooltipSource, /const focusVisible = event\.currentTarget\.matches\(':focus-visible'\)/)
  assert.match(tooltipSource, /pointerFocusedRef\.current = !focusVisible/)
  assert.match(tooltipSource, /if \(!focusVisible\) return/)
  assert.match(tooltipSource, /onPointerDown: handlePointerDown/)
  assert.match(tooltipSource, /if \(event\.button !== 0 \|\| event\.ctrlKey\) return/)
  assert.match(tooltipSource, /onPointerLeave: handlePointerLeave/)
  assert.match(tooltipSource, /<TooltipTrigger render=\{trigger\} disabled/)
  assert.match(tooltipSource, /onClick\?\.\(event\)[\s\S]*event\.stopPropagation\(\)/)
  assert.match(tooltipSource, /onPointerDown\?\.\(event\)[\s\S]*event\.stopPropagation\(\)/)
  assert.match(tooltipSource, /TOOLTIP_CLOSE_ANCHOR_CLEAR_DELAY_MS = 200/)
  assert.match(tooltipSource, /retimeFrozenPointerClear/)
  assert.match(tooltipSource, /'children' \| 'content'/)
  assert.match(tooltipSource, /anchorToCursor\?: boolean/)
  assert.match(tooltipSource, /anchorToCursor = true/)
  assert.match(tooltipSource, /new DOMRect\(frozenPointerPoint\.x, frozenPointerPoint\.y, 0, 0\)/)
  assert.match(tooltipSource, /const tooltipAnchor = anchorToCursor \? cursorAnchor : undefined/)
  assert.match(tooltipSource, /positionMethod=\{tooltipAnchor \? 'fixed' : undefined\}/)
  assert.match(tooltipSource, /side = 'bottom'/)
  assert.match(tooltipSource, /align = 'start'/)
  assert.match(tooltipSource, /instant = false/)
  assert.match(tooltipSource, /openInstantly: contentProps\.instant === true/)
  assert.match(tooltipSource, /if \(openInstantly\) \{[\s\S]*openTooltip\(point\)[\s\S]*return[\s\S]*\}/)
  assert.match(tooltipSource, /if \(closeInstantly\) \{[\s\S]*closeTooltip\(\)[\s\S]*return[\s\S]*\}/)
  assert.match(tooltipSource, /document\.elementFromPoint\(point\.x, point\.y\)/)
  assert.match(tooltipSource, /instant\s*\?\s*'transition-none'/)
  assert.match(tooltipSource, /TOOLTIP_EDGE_BORDER_ALIGN_OFFSET_PX = 1/)
  assert.match(tooltipSource, /alignOffset = TOOLTIP_EDGE_BORDER_ALIGN_OFFSET_PX/)
  assert.match(tooltipSource, /sideOffset = 16/)
  assert.match(tooltipSource, /arrowPadding = 0/)
  assert.match(tooltipSource, /collisionPadding = 4/)
  assert.match(tooltipSource, /TOOLTIP_COLLISION_AVOIDANCE/)
  assert.match(tooltipSource, /align: 'flip'/)
  assert.match(tooltipSource, /rounded-\[10px\]/)
  assert.match(tooltipSource, /data-\[align=start\]:data-\[side=bottom\]:rounded-tl-none/)
  assert.match(tooltipSource, /data-\[align=end\]:data-\[side=bottom\]:rounded-tr-none/)
  assert.match(tooltipSource, /\bwrap-anywhere\b/)
  assert.match(tooltipSource, /bg-\[canvas\]/)
  assert.match(tooltipSource, /shadow-lg shadow-\(color:--warm-gray\)/)
  assert.doesNotMatch(tooltipSource, /TooltipPrimitive\.Arrow/)
  assert.doesNotMatch(tooltipSource, /function ArrowSvg/)
  assert.match(tooltipSource, /TooltipAnchor/)
  assert.match(tooltipSource, /tooltipScrollableAncestors/)
  assert.match(tooltipSource, /tooltipScrollableAncestorsUnderPoint/)
  assert.match(tooltipSource, /document\.elementFromPoint\(x, y\)/)
  assert.match(tooltipSource, /uniqueTooltipScrollableAncestors/)
  assert.match(tooltipSource, /handleContentWheelRef/)
  assert.match(tooltipSource, /popupElement\.addEventListener\('wheel', handleWheel, \{\s*passive: false,\s*signal\s*\}\)/)
  assert.doesNotMatch(tooltipSource, /popupElement\.removeEventListener\('wheel', handleWheel\)/)
  assert.doesNotMatch(tooltipSource, /onWheel=\{handleContentWheel\}/)
  assert.match(pageChipSource, /chipTextTruncationCallbacks/)
  assert.match(pageChipSource, /getBoundingClientRect\(\)\.width/)
  assert.match(pageChipSource, /getBoundingClientRect\(\)\.height/)
  assert.match(pageChipSource, /useId\(\)/)
  assert.match(pageChipSource, /pageChipExpansionLane/)
  assert.match(pageChipSource, /useTitleExpansionController/)
  assert.match(pageChipSource, /PAGE_CHIP_EXPANDED_VIEWPORT_MARGIN_PX = 12/)
  assert.doesNotMatch(pageChipSource, /PAGE_CHIP_EXPANDED_MAX_WIDTH_OFFSET_PX/)
  assert.doesNotMatch(pageChipSource, /PAGE_CHIP_EXPANDED_CLOSE_DELAY_MS/)
  assert.doesNotMatch(pageChipSource, /PAGE_CHIP_EXPANDED_POINTER_LEAVE_TOLERANCE_PX/)
  assert.match(pageChipSource, /closeDelayMs: 0/)
  assert.match(pageChipSource, /chipExpansionController\.close\(\{ delayed: false \}\)/)
  assert.match(pageChipSource, /PAGE_CHIP_EXPANDED_WIDTH_GUARD_PX = 8/)
  assert.match(pageChipSource, /PAGE_CHIP_EXPANDED_WIDTH_SEARCH_STEPS = 12/)
  assert.match(pageChipSource, /function getVisibleChipTextLineCount\(textEl: HTMLElement \| null\)/)
  assert.match(
    pageChipSource,
    /function getExpandedPageChipLineHtml\(\s*textEl: HTMLElement \| null,\s*serializeFragment: ChipLineFragmentSerializer = expandedChipFragmentHtml,\s*geometry\?: ChipTextLineCaptureGeometry/
  )
  assert.match(
    pageChipSource,
    /function getClampedPageChipLineHtml\(\s*textEl: HTMLElement \| null,\s*geometry\?: ChipTextLineCaptureGeometry/
  )
  assert.match(pageChipSource, /function getExpandedPageChipContentWidth\(/)
  assert.match(pageChipSource, /function createExpandedPageChipMeasureElement\(/)
  assert.match(pageChipSource, /page-chip-expansion-measure/)
  assert.match(pageChipSource, /function getPageChipExpansionGeometry\(chipEl: HTMLElement \| null, textEl: HTMLElement \| null = chipEl\?\.querySelector/)
  assert.match(pageChipSource, /const roomToRight = Math\.max\(0, viewportWidth - rect\.left - PAGE_CHIP_EXPANDED_VIEWPORT_MARGIN_PX\)/)
  assert.match(pageChipSource, /const maxWidth = Math\.max\(rect\.width, roomToRight\)/)
  assert.match(pageChipSource, /x: 'start'/)
  assert.match(pageChipSource, /chipExpanded && 'left-0'/)
  assert.doesNotMatch(pageChipSource, /roomToLeft/)
  assert.doesNotMatch(pageChipSource, /shouldAnchorEnd/)
  assert.doesNotMatch(pageChipSource, /chipExpansionGeometry\.x === 'end'/)
  assert.match(pageChipSource, /lineHtml = getExpandedPageChipLineHtml\(textEl\)/)
  assert.match(pageChipSource, /function expansionRevealsHydratingPills\(textEl: HTMLElement\)/)
  assert.match(pageChipSource, /function measureConstrainedPackedWidth\(measureEl: HTMLElement, maxContentWidth: number\)/)
  assert.match(pageChipSource, /'\.chip-title-suppression-marker, \.chip-strip-indicator\[aria-label\]'/)
  assert.doesNotMatch(pageChipSource, /expansionCapturedLinesRewrapOnExpand/)
  assert.match(pageChipSource, /const contentBoxEl = chipEl\.querySelector<HTMLElement>\('\.chip-text'\) \|\| textEl/)
  assert.match(pageChipSource, /function titleVariantLabelsOverflow\(textEl: HTMLElement \| null\) \{[\s\S]*\.chip-title-variant-label[\s\S]*scrollWidth[\s\S]*clientWidth/)
  assert.match(pageChipSource, /titleVariantLabelsOverflow\(textEl\) \|\| titleVariantContentOverflows\(textEl\)/)
  assert.match(pageChipSource, /function getTitleVariantMinimumContentWidth\(textEl: HTMLElement \| null\)/)
  assert.match(pageChipSource, /Math\.max\(getChipTextExpansionBaselineWidth\(contentBoxEl\), getTitleVariantMinimumContentWidth\(contentBoxEl\)\)/)
  assert.match(pageChipSource, /width: Math\.min\(maxWidth, Math\.max\(rect\.width, minWidth, contentMetrics\.width \+ horizontalInset\)\)/)
  assert.match(pageChipSource, /function roundedElementSize\(element: HTMLElement \| null\)/)
  assert.match(pageChipSource, /const \[chipSlotSize, setChipSlotSize\] = useState\(DEFAULT_CHIP_SLOT_SIZE\)/)
  assert.match(pageChipSource, /const \[chipExpansionGeometry, setChipExpansionGeometry\] = useState\(DEFAULT_CHIP_EXPANSION_GEOMETRY\)/)
  assert.match(pageChipSource, /left\.grewTaller === right\.grewTaller/)
  assert.doesNotMatch(pageChipSource, /if \(!chipExpandedRef\.current\) updateChipSlotMeasurements\(chipEl\)/)
  assert.doesNotMatch(pageChipSource, /observer\.observe\(chipEl\)/)
  // openChipExpansion must not re-measure while already expanded: re-deriving the
  // expansion geometry from the hydrated expanded DOM duplicates suppression markers
  // (regression: right-clicking an already-expanded chip duplicated the marker).
  assert.match(pageChipSource, /function openChipExpansion\(\) \{[\s\S]*if \(!chipExpandedRef\.current\) \{[\s\S]*updateChipSlotMeasurements\(\)[\s\S]*\}/)
  assert.match(pageChipSource, /pageTargetMatchUrls\(target\)/)
  assert.match(pageChipSource, /pageTargetMatchesHover\(target, state\.url, state\.urls\)/)
  assert.match(pageChipOverflowSource, /pageTargetMatchesHover\(chip, state\.url, state\.urls\)/)
  assert.match(pageChipSource, /chip-text-expansion-hit-area -my-1\.25[\s\S]*py-1\.25/)
  assert.match(pageChipSource, /function onChipPointerEnter\(\) \{[\s\S]*openChipExpansion\(\)/)
  assert.match(pageChipSource, /function isPointerInsideChipSlot\(e: PointerEvent<HTMLDivElement>\) \{[\s\S]*chipSlotRef\.current\?\.getBoundingClientRect\(\)/)
  assert.match(pageChipSource, /function onChipPointerMove\(e: PointerEvent<HTMLDivElement>\) \{[\s\S]*chipExpandedRef\.current[\s\S]*isPointerInsideChipSlot\(e\)[\s\S]*openChipExpansion\(\)/)
  assert.match(pageChipSource, /function setDefaultVariantSurfaceHover\(active: boolean\) \{[\s\S]*toggleAttribute\('data-tabout-default-surface-hover', active\)/)
  assert.match(pageChipSource, /function previewDefaultTitleVariantSurface\(target: EventTarget \| null\) \{[\s\S]*setDefaultVariantSurfaceHover\(true\)[\s\S]*previewDefaultTitleVariant\(\)/)
  assert.match(pageChipSource, /function onVariantGroupChipMouseEnter\(e: MouseEvent<HTMLDivElement>\) \{\n\s*if \(!previewDefaultTitleVariantSurface\(e\.target\)\) return\n\s*openChipExpansion\(\)\n\s*\}/)
  assert.match(pageChipSource, /function onVariantGroupChipMouseMove\(e: MouseEvent<HTMLDivElement>\) \{\n\s*if \(!previewDefaultTitleVariantSurface\(e\.target\)\) return\n\s*if \(chipExpandedRef\.current\) return\n\s*openChipExpansion\(\)\n\s*\}/)
  assert.match(pageChipSource, /function onTitleVariantMouseEnter\(variant: DashboardChipData\) \{\n\s*setDefaultVariantSurfaceHover\(false\)/)
  assert.match(baseStylesheet, /\.chip-slot\[data-tabout-default-surface-hover\] \.chip-title-variant\[data-tabout-default-variant\]/)
  assert.match(pageChipSource, /onPointerEnter=\{onChipPointerEnter\}/)
  assert.match(pageChipSource, /onPointerMove=\{onChipPointerMove\}/)
  assert.match(pageChipSource, /onMouseMove:\s*onVariantGroupChipMouseMove/)
  assert.doesNotMatch(pageChipSource, /onPointerEnter=\{onChipTextExpansionHitAreaPointerEnter\}/)
  assert.match(pageChipSource, /const titleVariantTitleExpansionTriggerElement = \(/)
  assert.match(pageChipSource, /const foldedTitleExpansionTriggerElement = \(/)
  assert.doesNotMatch(pageChipSource, /titleVariantTooltipContentNode/)
  assert.doesNotMatch(pageChipSource, /getChipTooltipAnchor/)
  assert.doesNotMatch(pageChipSource, /chip-text-tooltip-hit-area/)
  assert.match(pageChipSource, /page-chip-tooltip-open/)
  // The interaction-fill and outline strings live behind the chip-trim
  // interface and are covered by tests/chip-trim.test.ts; here we only pin
  // that PageChip consumes the module's vars.
  assert.match(pageChipSource, /--chip-hover-border': trim\.styleVars\.hoverBorder/)
  assert.match(pageChipSource, /page-chip-expanded absolute z-30/)
  assert.match(pageChipSource, /page-chip-expanded absolute z-30 min-w-0/)
  assert.match(pageChipSource, /max-w-\(--page-chip-expanded-max-width\)/)
  assert.match(pageChipSource, /transition-none!/)
  assert.match(pageChipSource, /w-\(--page-chip-expanded-width\)/)
  assert.match(pageChipSource, /shadow-\[0_3px_10px_rgba\(10,10,10,0\.055\)\]/)
  assert.match(pageChipSource, /const closeOnPointerMove = \(event: globalThis\.PointerEvent\) =>/)
  assert.match(pageChipSource, /chipSlotRef\.current\?\.getBoundingClientRect\(\)/)
  assert.match(pageChipSource, /window\.addEventListener\('pointermove', closeOnPointerMove, true\)/)
  assert.match(pageChipSource, /window\.removeEventListener\('pointermove', closeOnPointerMove, true\)/)
  assert.match(pageChipSource, /'--page-chip-expanded-width': chipExpandedWidth/)
  assert.match(pageChipSource, /'--chip-interaction-bg': trim\.styleVars\.interactionBg/)
  assert.doesNotMatch(pageChipSource, /backgroundColor: 'var\(--chip-hover-fade-bg\)'/)
  assert.match(pageChipSource, /width: chipExpandedWidth/)
  assert.match(pageChipSource, /page-chip-expanded-line/)
  assert.match(pageChipSource, /expansionLineNodesFromHtml/)
  assert.match(pageChipSource, /data-expanded=\{chipExpanded \? 'true' : undefined\}/)
  assert.match(pageChipSource, /data-tabout-part="slot"/)
  assert.match(pageChipSource, /chip-slot relative min-w-0/)
  assert.match(pageChipSource, /PAGE_CHIP_TOOLTIP_SUPPRESSION_MARKER_CLASS_NAME/)
  assert.doesNotMatch(pageChipSource, /hover:bg-\[rgba\(10,10,10,0\.12\)\]/)
  assert.doesNotMatch(pageChipSource, /\[\&\.page-chip-context-menu-open\]:bg-\[rgba\(10,10,10,0\.12\)\]/)
  assert.match(pageChipSource, /group-\[\.page-chip-expanded\]\/page-chip:hidden/)
  assert.match(pageChipSource, /group-\[\.page-chip-expanded\]\/page-chip:inline/)
  assert.match(pageChipSource, /whitespace-nowrap/)
  assert.doesNotMatch(pageChipSource, /page-chip-tooltip-measure/)
  assert.doesNotMatch(pageChipSource, /page-chip-tooltip-line/)
  assert.doesNotMatch(pageChipSource, /dangerouslySetInnerHTML/)
  assert.match(pageChipSource, /chipTextContentNode\(mode: ChipTextRenderMode\)/)
  assert.match(pageChipSource, /chipTextContentNode\('tooltip'\)/)
  assert.match(pageChipSource, /chipTextContentNode\('chip'\)/)
  assert.match(pageChipSource, /page-chip-tooltip max-w-\[calc\(100vw-16px\)\] text-\[13px\] leading-tight wrap-break-word/)
  assert.match(pageChipSource, /hyphens-auto break-normal/)
  assert.match(pageChipSource, /inline-block max-w-\[calc\(100%-6px\)\] whitespace-normal break-normal w-max wrap-break-word/)
  assert.doesNotMatch(pageChipSource, /duplicateLabel \|\| activeLabel/)
  assert.doesNotMatch(pageChipSource, /\? chip\.tooltip : undefined/)
  assert.doesNotMatch(pageChipSource, /@chenglou\/pretext/)
  assert.match(tabHistoryPanelSource, /historyTitleTruncationCallbacks/)
  assert.match(tabHistoryPanelSource, /HISTORY_ENTRY_EXPANDED_VIEWPORT_MARGIN_PX = 12/)
  assert.doesNotMatch(tabHistoryPanelSource, /HISTORY_ENTRY_EXPANDED_CLOSE_DELAY_MS/)
  assert.match(tabHistoryPanelSource, /closeDelayMs: 0/)
  assert.match(tabHistoryPanelSource, /HISTORY_ENTRY_EXPANDED_WIDTH_GUARD_PX = 8/)
  assert.match(tabHistoryPanelSource, /useState\(DEFAULT_HISTORY_TITLE_LAYOUT_STATE\)/)
  assert.match(tabHistoryPanelSource, /titleEl\.scrollHeight - titleEl\.clientHeight > 1/)
  assert.match(tabHistoryPanelSource, /getHistoryTitleContentWidth/)
  assert.match(tabHistoryPanelSource, /getHistoryTitleExpandedLineHtml/)
  assert.match(tabHistoryPanelSource, /historyTitleExpandedLineMarkup/)
  assert.match(tabHistoryPanelSource, /expansionLineNodesFromHtml/)
  assert.match(tabHistoryPanelSource, /expandedViewportConstrained/)
  assert.match(tabHistoryPanelSource, /visibleLineCount/)
  assert.match(tabHistoryPanelSource, /getBoundingClientRect\(\)\.width/)
  assert.match(tabHistoryPanelSource, /historyEntryExpansionLane/)
  assert.match(tabHistoryPanelSource, /useTitleExpansionController/)
  assert.match(tabHistoryPanelSource, /function getHistoryTitleExpandedTextWidth\(/)
  assert.match(tabHistoryPanelSource, /history-entry-title-expansion-measure/)
  assert.match(tabHistoryPanelSource, /--history-entry-expanded-width/)
  assert.match(tabHistoryPanelSource, /const \[titleExpanded, setTitleExpandedState\] = useState\(false\)/)
  assert.match(tabHistoryPanelSource, /titleExpanded && 'history-entry-expanded-open'/)
  assert.match(tabHistoryPanelSource, /titleExpanded && 'history-entry-row-expanded-open'/)
  assert.match(tabHistoryPanelSource, /function openTitleExpansion\(\) \{[\s\S]*updateHistoryEntryExpansionMeasurements\(\)[\s\S]*titleExpansionController\.open\(\)/)
  assert.doesNotMatch(tabHistoryPanelSource, /if \(!titleExpandedRef\.current\) updateHistoryEntryExpansionMeasurements\(\)/)
  assert.doesNotMatch(tabHistoryPanelSource, /observer\.observe\(entryEl\)/)
  assert.match(tabHistoryPanelSource, /function closeTitleExpansion\(\) \{[\s\S]*titleExpansionController\.close\(\{ delayed: false \}\)/)
  assert.match(tabHistoryPanelSource, /function onHistoryEntryPointerEnter\(\) \{[\s\S]*openTitleExpansion\(\)/)
  assert.match(tabHistoryPanelSource, /function onHistoryEntryPointerMove\(e: PointerEvent<HTMLDivElement>\)/)
  assert.match(tabHistoryPanelSource, /window\.addEventListener\('pointermove', closeOnPointerMove, true\)/)
  assert.match(tabHistoryPanelSource, /history-entry-title-expansion-hit-area/)
  assert.match(tabHistoryPanelSource, /pageTargetMatchesHover\(entry, state\.url, state\.urls\)/)
  assert.match(tabHistoryPanelSource, /HISTORY_ENTRY_CLICKABLE_INTERACTION_BG = 'color-mix\(in srgb, var\(--card-bg\) 90%, var\(--color-neutral-600\) 10%\)'/)
  assert.match(tabHistoryPanelSource, /HISTORY_ENTRY_INTERACTION_CLASSES = 'group-hover\/history-row:bg-\(--history-entry-interaction-bg\)[\s\S]*\[\&\.history-entry-expanded-open\]:bg-\(--history-entry-interaction-bg\)/)
  assert.match(tabHistoryPanelSource, /HISTORY_ENTRY_ACTIVE_OTHER_INTERACTION_CLASSES = `bg-\(--history-entry-rest-bg\)/)
  assert.match(tabHistoryPanelSource, /history-entry-expanded-line-tail/)
  assert.match(tabHistoryPanelSource, /data-expanded=\{titleExpanded \? 'true' : undefined\}/)
  assert.match(tabHistoryPanelSource, /function getHistoryEntryExpansionGeometry\(entryEl: HTMLElement \| null, titleEl: HTMLElement \| null\)/)
  assert.match(tabHistoryPanelSource, /const expandedEntryElement = titleExpanded \? historyEntrySurface\(true\) : null/)
  assert.match(tabHistoryPanelSource, /history-entry-list pointer-events-none relative flex min-h-0[^"]*scrollbar-none[^"]*max-\[900px\]:w-auto[^"]*max-\[900px\]:mr-\[calc\(var\(--dashboard-edge-bleed\)-var\(--dashboard-scrollbar-inset\)\)\]/)
  assert.doesNotMatch(tabHistoryPanelSource, /history-entry-list pointer-events-none relative z-/)
  assert.match(tabHistoryPanelSource, /history-entry-list-content pointer-events-auto flex self-start w-65[^"]*pb-10[^"]*max-\[900px\]:pr-0[^"]*max-\[900px\]:pb-3/)
  assert.match(tabHistoryPanelSource, /history-entry-scrollbar pointer-events-none absolute top-0 right-0 bottom-0 z-20 w-\(--dashboard-scrollbar-size\) select-none max-\[900px\]:right-\[calc\(0px-var\(--dashboard-scrollbar-inset\)\)\]/)
  assert.match(tabHistoryPanelSource, /history-entry-scrollbar-track pointer-events-auto absolute top-\(--dashboard-scrollbar-padding\) right-0 bottom-\(--dashboard-scrollbar-padding\) w-\(--dashboard-scrollbar-size\)/)
  assert.match(tabHistoryPanelSource, /onPointerDown=\{onTrackPointerDown\}/)
  assert.match(tabHistoryPanelSource, /history-entry-scrollbar-thumb absolute top-0 right-0 w-\(--dashboard-scrollbar-size\) rounded-\(--dashboard-scrollbar-radius\) border-\(length:--dashboard-scrollbar-padding\) border-transparent bg-\(--dashboard-scrollbar-thumb-bg\) bg-clip-content/)
  // Thumb widens on hover by shrinking its transparent border, mirroring the native
  // .scroll-region::-webkit-scrollbar-thumb:hover rule so both rails expand alike.
  assert.match(tabHistoryPanelSource, /history-entry-scrollbar-thumb[^']*hover:border-\(length:--dashboard-scrollbar-padding-hover\)/)
  // The grow animates border-width over the shared duration, and stays wide for the whole drag.
  assert.match(tabHistoryPanelSource, /\[transition:opacity_300ms_ease-out,border-width_var\(--dashboard-scrollbar-grow-duration\)_ease-out\]/)
  assert.match(tabHistoryPanelSource, /dragging && 'border-\(length:--dashboard-scrollbar-padding-hover\)'/)
  assert.doesNotMatch(tabHistoryPanelSource, /group-hover\/history-scrollbar-track:w-\(--dashboard-scrollbar-size\)/)
  assert.doesNotMatch(tabHistoryPanelSource, /transition-\[opacity,width,right\]/)
  assert.doesNotMatch(tabHistoryPanelSource, /cursor-grab/)
  assert.doesNotMatch(tabHistoryPanelSource, /cursor-grabbing/)
  assert.match(tabHistoryPanelSource, /onPointerDown=\{onThumbPointerDown\}/)
  assert.match(tabHistoryPanelSource, /--history-entry-scrollbar-thumb-height/)
  assert.match(tabHistoryPanelSource, /className="history-entry-slot relative min-w-0 flex-auto"[\s\S]*\{historyEntrySurface\(false\)\}[\s\S]*\{expandedEntryElement\}/)
  // The expansion no longer collapses on scroll; it stays open until the pointer
  // leaves the entry's slot (or window blur / tab hidden).
  assert.doesNotMatch(tabHistoryPanelSource, /closeExpandedHistoryEntryBeforeNativeScroll/)
  assert.doesNotMatch(tabHistoryPanelSource, /closeExpandedHistoryEntryOnNativeScroll/)
  assert.doesNotMatch(tabHistoryPanelSource, /onWheelCapture=/)
  assert.doesNotMatch(tabHistoryPanelSource, /onScrollCapture=/)
  assert.doesNotMatch(tabHistoryPanelSource, /window\.addEventListener\('scroll'/)
  assert.doesNotMatch(tabHistoryPanelSource, /function getHistoryEntryLayerRoot/)
  assert.doesNotMatch(tabHistoryPanelSource, /layerElement\?: HTMLElement \| null/)
  assert.doesNotMatch(tabHistoryPanelSource, /const \[historyPanelElement, setHistoryPanelElement\]/)
  assert.doesNotMatch(tabHistoryPanelSource, /createPortal/)
  assert.doesNotMatch(tabHistoryPanelSource, /history-entry-overlay/)
  assert.doesNotMatch(tabHistoryPanelSource, /onHistoryEntryWheel/)
  assert.doesNotMatch(tabHistoryPanelSource, /historyWheelGestureActive/)
  assert.doesNotMatch(tabHistoryPanelSource, /onWheel=\{/)
  assert.doesNotMatch(tabHistoryPanelSource, /scrollTop\s*=/)
  assert.match(tabHistoryPanelSource, /history-entry-expanded pointer-events-none absolute left-0 z-30/)
  assert.doesNotMatch(tabHistoryPanelSource, /history-entry-expanded pointer-events-auto/)
  assert.match(tabHistoryPanelSource, /data-tabout-part="history-scrollbar-input-shield"/)
  assert.match(tabHistoryPanelSource, /history-entry-scrollbar-input-shield pointer-events-auto absolute top-0 bottom-0 z-3/)
  assert.match(tabHistoryPanelSource, /scrollbarShieldLeft/)
  assert.match(tabHistoryPanelSource, /scrollbarShieldWidth/)
  assert.doesNotMatch(tabHistoryPanelSource, /history-entry-expanded fixed z-30/)
  assert.match(tabHistoryPanelSource, /shadow-\[0_3px_10px_rgba\(10,10,10,0\.055\)\]/)
  assert.doesNotMatch(tabHistoryPanelSource, /history-entry-title-expansion line-clamp-2/)
  assert.match(tabHistoryPanelSource, /w-\(--history-entry-expanded-title-width\)/)
  assert.doesNotMatch(tabHistoryPanelSource, /\[text-wrap:balance\]/)
  assert.doesNotMatch(tabHistoryPanelSource, /w-max/)
  assert.doesNotMatch(tabHistoryPanelSource, /TooltipAnchor/)
  assert.doesNotMatch(tabHistoryPanelSource, /getHistoryTitleTooltipAnchor/)
  assert.doesNotMatch(tabHistoryPanelSource, /anchorToCursor=\{false\}/)
  assert.doesNotMatch(tabHistoryPanelSource, /sideOffset=\{0\}/)
  assert.doesNotMatch(tabHistoryPanelSource, /history-entry-title-tooltip/)
  assert.match(tabHistoryPanelSource, /wrap-break-word/)
  assert.match(tabHistoryPanelSource, /\[font-family:inherit\]/)
  assert.match(tabHistoryPanelSource, /focus-within:shadow-\[inset_0_0_0_1px_rgba\(234,179,8,0\.42\)\]/)
  assert.match(tabHistoryPanelSource, /history-entry group\/history-entry[^"]*rounded-\[10px\][^"]*border-0[^"]*bg-transparent/)
  assert.match(tabHistoryPanelSource, /history-entry-title block min-w-0 flex-auto overflow-hidden hyphens-auto break-normal max-h-\[calc\(2lh\)\]/)
  assert.match(tabHistoryPanelSource, /\[\&\.history-entry-title-truncated\]:mask-\(--title-fade-mask\)/)
  assert.doesNotMatch(tabHistoryPanelSource, /history-entry-title line-clamp-2/)
  assert.match(tabHistoryPanelSource, /group-hover\/history-row:bg-\(--history-entry-interaction-bg\)/)
  assert.doesNotMatch(tabHistoryPanelSource, /border border-\(--warm-gray\)/)
  assert.doesNotMatch(tabHistoryPanelSource, /group-hover\/history-row:border-\(--accent-amber\)/)
  assert.match(tabHistoryPanelSource, /after:w-0/)
  assert.doesNotMatch(tabHistoryPanelSource, /after:w-14/)
  assert.match(tabHistoryPanelSource, /className="history-entry-main flex w-full[^"]*cursor-default[^"]*items-start[^"]*focus-visible:outline-none/)
  assert.doesNotMatch(tabHistoryPanelSource, /history-entry group\/history-entry[^"]*\bmin-h-/)
  assert.doesNotMatch(tabHistoryPanelSource, /history-entry-main[^"]*\bmin-h-/)
  assert.doesNotMatch(tabHistoryPanelSource, /history-entry-row[^"]*\bmin-h-/)
  assert.match(tabHistoryPanelSource, /className="history-entry-close history-entry-close-favicon pointer-events-none absolute[^"]*group-hover\/history-favicon-frame:pointer-events-auto[^"]*focus-visible:outline-2/)
  assert.doesNotMatch(tabHistoryPanelSource, /history-entry group\/history-entry[^"]*\btransition-/)
  assert.doesNotMatch(tabHistoryPanelSource, /className="history-entry-close history-entry-close-favicon[^"]*\btransition-/)
  assert.doesNotMatch(tabHistoryPanelSource, /<TooltipAnchor/)
  assert.match(pathgroupSectionSource, /pathgroupLabelTruncated \? \(/)
  assert.match(pathgroupSectionSource, /className="text-\[13px\] leading-tight"/)
  assert.doesNotMatch(pathgroupSectionSource, /<TooltipAnchor content=\{displayLabel\}>/)
  assert.match(tooltipSource, /mergeRefs<HTMLElement>\(children\.props\.ref, triggerElementRef\)/)
  assert.match(tooltipSource, /children\.props\.ref/)
  assert.match(selectSource, /@base-ui\/react\/select/)
  assert.match(selectSource, /lucide-react/)
  assert.match(selectSource, /@\/lib\/utils/)
  assert.match(utilsSource, /export \{ cn \} from 'cnfast'/)
  assert.doesNotMatch(utilsSource, /from 'clsx'/)
  assert.doesNotMatch(utilsSource, /from 'tailwind-merge'/)
  assert.equal(existsSync('src/lib/cn.ts'), false)
  assert.match(appStylesheet, /--color-input:/)
  assert.match(appStylesheet, /--color-popover:/)
  assert.match(appStylesheet, /--color-popover-foreground:/)
  assert.match(appStylesheet, /--color-ring:/)
  assert.match(selectSource, /data-slot="select-trigger"/)
  assert.match(selectSource, /data-size=\{size\}/)
  assert.match(selectSource, /border-input bg-transparent py-2 pr-2 pl-2\.5 text-sm whitespace-nowrap transition-colors/)
  assert.match(selectSource, /data-placeholder:text-muted-foreground/)
  assert.match(selectSource, /data-slot="select-content"/)
  assert.match(selectSource, /max-h-\(--available-height\) w-\(--anchor-width\) min-w-36/)
  assert.match(selectSource, /SelectPrimitive\.ScrollUpArrow/)
  assert.match(selectSource, /SelectPrimitive\.ScrollDownArrow/)
  assert.match(selectSource, /SelectPrimitive\.ItemIndicator/)
  assert.match(selectSource, /SelectPrimitive\.ItemText className="flex flex-1 shrink-0 gap-2 whitespace-nowrap"/)
  assert.match(selectSource, /pointer-events-none absolute right-2 flex size-4 items-center justify-center/)
  assert.match(selectSource, /ChevronDownIcon/)
  assert.match(selectSource, /ChevronUpIcon/)
  assert.match(selectSource, /data-slot="select-scroll-up-button"/)
  assert.match(selectSource, /data-slot="select-scroll-down-button"/)
  assert.match(selectSource, /align = 'center'/)
  assert.match(selectSource, /alignItemWithTrigger = true/)
  assert.match(selectSource, /data-align-trigger/)
  assert.doesNotMatch(headerBarSource, /from '\.\/ui\/button'/)
  assert.doesNotMatch(headerBarSource, /from '\.\/ui\/input'/)
  assert.doesNotMatch(headerBarSource, /from '\.\/ui\/select'/)
  assert.match(headerBarSource, /from '\.\/ui\/tabs'/)
  assert.match(appComponentSource, /historyRangeSelectImport \?\?= import\('\.\/HistoryRangeSelect'\)/)
  assert.match(appComponentSource, /lazy\(\(\) => loadHistoryRangeSelect\(\)\.then/)
  assert.match(appComponentSource, /nextFilterInput\.trim\(\)[\s\S]*loadHistoryRangeSelect\(\)/)
  assert.match(appComponentSource, /fallback=\{<HistoryRangeSelectFallback value=\{historyRange\} \/>\}/)
  assert.match(historyRangeSelectSource, /function HistoryRangeSelect/)
  assert.match(historyRangeSelectSource, /<Select value=\{value\} items=\{HISTORY_RANGE_OPTIONS\} onValueChange=\{handleValueChange\}>/)
  assert.match(historyRangeSelectSource, /<SelectTrigger[\s\S]*className="[^"]*bg-tab-card/)
  assert.doesNotMatch(historyRangeSelectSource, /<SelectTrigger\s+className="[^"]*bg-\[rgba\(115,115,115,0\.06\)\]/)
  assert.match(historyRangeSelectSource, /<SelectContent[\s\S]*align="start"[\s\S]*className="[^"]*rounded-\(--header-control-radius\)/)
  assert.doesNotMatch(historyRangeSelectSource, /alignItemWithTrigger=\{false\}/)
  assert.match(historyRangeSelectSource, /<SelectGroup>/)
  assert.match(historyRangeSelectSource, /<SelectItem[\s\S]*key=\{option\.value\}[\s\S]*value=\{option\.value\}[\s\S]*label=\{option\.label\}/)
  assert.doesNotMatch(historyRangeSelectSource, /aria-selected:bg-accent|aria-selected:text-accent-foreground/)
  assert.doesNotMatch(headerBarSource, /SelectControl|TextInput|SegmentedTabs/)
  assert.match(appComponentSource, /missions-divider mb-4 flex items-center gap-3/)
  assert.match(appComponentSource, /missions-divider-action shrink-0/)
  assert.doesNotMatch(appComponentSource, /missions-divider-action[^"]*mr-3/)
  assert.doesNotMatch(appComponentSource, /missions-divider-action[^"]*bg-\(--paper\)/)
  assert.match(appComponentSource, /missions-divider-label pointer-events-none shrink-0 whitespace-nowrap/)
  assert.doesNotMatch(appComponentSource, /missions-divider-label[^"]*absolute/)
  assert.doesNotMatch(appComponentSource, /missions-divider-label[^"]*bg-\(--paper\)/)
  assert.match(appComponentSource, /missions-divider-label[\s\S]*missions-divider-action[\s\S]*missions-divider-rule/)
  assert.deepEqual(uiFiles, ['context-menu-registry.ts', 'context-menu.tsx', 'menu-styles.ts', 'menu.tsx', 'select.tsx', 'tabs.tsx', 'tooltip.tsx'])
  assert.match(toastSource, /p-4!/)
  assert.match(toastSource, /mt-2!/)
  assert.match(toastSource, /px-3!/)
  assert.match(toastSource, /fixed bottom-4 left-4 right-auto top-auto/)
  assert.match(toastSource, /min-\[500px\]:left-8/)
  assert.match(toastSource, /origin-\[bottom_center\]/)
  assert.doesNotMatch(toastSource, /origin-\[bottom_left\]/)
  assert.doesNotMatch(toastSource, /min-\[500px\]:right-8/)
  assert.match(toastSource, /rounded-3xl \[corner-shape:squircle\]/)
  assert.match(toastSource, /<BaseToast\.Content className="[^"]*data-behind:opacity-0/)
  assert.match(toastSource, /rounded-xl \[corner-shape:squircle\]/)
  assert.match(toastSource, /rounded-full border-0 bg-transparent/)
  assert.match(toastSource, /<XIcon className="size-3" \/>/)
  assert.match(toastSource, /\[corner-shape:squircle\]/)
  assert.doesNotMatch(toastSource, /rounded-sm/)
  assert.match(baseStylesheet, /button,\ninput,\nselect,\ntextarea\s*\{\n\s*font-family: inherit;/)
  assert.match(appComponentSource, /'scroll-region[^']*overflow-x-hidden[^']*overflow-y-auto[^']*overscroll-y-contain[^']*'/)
  assert.match(baseStylesheet, /--dashboard-scrollbar-size: 10px;/)
  assert.match(baseStylesheet, /--dashboard-scrollbar-padding: 2px;/)
  assert.match(baseStylesheet, /--dashboard-scrollbar-thumb-size: 6px;/)
  assert.match(baseStylesheet, /--dashboard-scrollbar-padding-hover: 1px;/)
  assert.match(baseStylesheet, /--dashboard-scrollbar-thumb-size-hover: 8px;/)
  assert.match(baseStylesheet, /--dashboard-scrollbar-grow-duration: 200ms;/)
  assert.match(baseStylesheet, /--dashboard-scrollbar-radius: 10px;/)
  assert.match(baseStylesheet, /--dashboard-scrollbar-thumb-bg: rgba\(0, 0, 0, 0\.44\);/)
  assert.match(baseStylesheet, /--dashboard-scrollbar-thumb-bg-hover: rgba\(0, 0, 0, 0\.55\);/)
  assert.match(baseStylesheet, /--dashboard-scrollbar-thumb-bg-active: rgba\(0, 0, 0, 0\.66\);/)
  // The scroll-region must NOT carry the standard scrollbar-width / scrollbar-color
  // properties: in Chromium they take precedence over the ::-webkit-scrollbar rules
  // below and force a standard/overlay bar that ignores the shared 8px/4px tokens and
  // no longer matches the Activation History thumb. The native track width is pinned
  // in the browser smoke test; this guards the source so the props can't creep back in.
  assert.doesNotMatch(appComponentSource, /'scroll-region[^']*\[scrollbar-color:/)
  assert.doesNotMatch(appComponentSource, /'scroll-region[^']*\[scrollbar-width:/)
  assert.match(appComponentSource, /'scroll-region[^']*max-\[900px\]:\[\.dashboard-main_>&\]:mr-\[calc\(var\(--dashboard-scrollbar-size\)-var\(--dashboard-scrollbar-thumb-size\)-var\(--dashboard-edge-bleed\)\)\][^']*max-\[900px\]:\[\.dashboard-main_>&\]:pr-\[calc\(var\(--dashboard-edge-bleed\)-var\(--dashboard-scrollbar-size\)\+var\(--dashboard-scrollbar-thumb-size\)\)\]/)
  assert.match(baseStylesheet, /\.scroll-region::-webkit-scrollbar\s*\{[\s\S]*width: var\(--dashboard-scrollbar-size\);/)
  assert.match(baseStylesheet, /\.scroll-region::-webkit-scrollbar-thumb\s*\{[\s\S]*min-height: 33px;[\s\S]*border: var\(--dashboard-scrollbar-padding\) solid transparent;[\s\S]*background: var\(--dashboard-scrollbar-thumb-bg\);/)
  assert.match(baseStylesheet, /\.scroll-region::-webkit-scrollbar-thumb:hover\s*\{\n\s*border-width: var\(--dashboard-scrollbar-padding-hover\);\n\s*background: var\(--dashboard-scrollbar-thumb-bg-hover\);\n\s*background-clip: content-box;\n\}/)
  assert.match(baseStylesheet, /\.scroll-region::-webkit-scrollbar-thumb:active\s*\{\n\s*border-width: var\(--dashboard-scrollbar-padding-hover\);\n\s*background: var\(--dashboard-scrollbar-thumb-bg-active\);\n\s*background-clip: content-box;\n\}/)
  assert.match(pageChipSource, /'chip-favicon-stack-layer [^']*absolute top-0 left-0[^']*size-4[^']*rounded-sm/)
  assert.doesNotMatch(pageChipSource, /'chip-favicon-stack-layer [^']*inset-0/)
  assert.match(pageChipSource, /dupeCount > 2 && \(/)
  assert.match(pageChipSource, /'chip-page-pin-badge [^']*data-\[pinned=true\]:opacity-100/)
  assert.doesNotMatch(pageChipSource, /chip-dupe-badge pointer-events-none absolute -top/)
  assert.match(pageChipSource, /dedupeBadgesClosing && 'closing'/)
  assert.match(domainCardContextSource, /createContext\(defaultDomainCardContext\)/)
  assert.match(domainCardSource, /<DomainCardProvider value=\{cardContext\}>/)
  assert.match(dashboardInteractionContextSource, /createHoverStateStore/)
  assert.match(dashboardInteractionContextSource, /subscribeSelector/)
  assert.match(dashboardInteractionContextSource, /useSyncExternalStore/)
  assert.match(useHoverMatchSource, /const \[hoverStateStore\] = useState\(createHoverStateStore\)/)
  assert.match(useHoverMatchSource, /function sameHoverUrls/)
  assert.match(useHoverMatchSource, /function handleHoverUrlChange\(url: string, source: HoverUrlSource = 'chip', matchUrls\?: readonly string\[\], tabId\?: number\)/)
  assert.match(useHoverMatchSource, /nativeTabHighlightController\.setTarget\(nextUrl \? tabId : null\)/)
  assert.match(pageChipSource, /function setPreview\(url: string, matchUrls: readonly string\[\] = \[url\], target\?: Pick<DashboardChipData, 'tabId'>\)[\s\S]*onHoverUrlChange\?\.\(url \|\| '', 'chip', matchUrls, tabId\)/)
  assert.match(pageChipSource, /async function activateChipTarget\([\s\S]*await setPreview\(''\)[\s\S]*performDashboardItemActivation/)
  assert.match(pageChipSource, /function onEnvClick\(e: MouseEvent<HTMLButtonElement>, env: DashboardChipEnv\)[\s\S]*await activateChipTarget\(e, env\.tabUrl, env\.sourceType \|\| chip\.sourceType, env, e\.currentTarget\)/)
  assert.match(tabHistoryPanelSource, /async function activateHistoryEntry\([\s\S]*await onHoverUrlChange\?\.\(''\)[\s\S]*chipActivationMode/)
  assert.match(tabHistoryPanelSource, /const tabId = workingSetItem\?\.tabId \?\? \(entry\.exists \? entry\.tabId : undefined\)[\s\S]*onHoverUrlChange\?\.\(hoverUrl, hoverSource, hoverUrls, tabId\)/)
  assert.match(useHoverMatchSource, /hoverStateStore\.setSnapshot/)
  assert.match(useHoverMatchSource, /setUrlPreview\(nextUrl\)/)
  assert.match(useUrlPreviewSource, /URL_PREVIEW_HIDE_DELAY_MS = 120/)
  assert.match(appComponentSource, /<HoverStateProvider store=\{hoverStateStore\}>/)
  assert.match(appComponentSource, /<UrlPreview store=\{urlPreviewStore\}/)
  assert.match(tabHistoryPanelSource, /useHoverStateSelector/)
  assert.match(`${flatSectionSource}\n${pageChipSource}\n${pathgroupSectionSource}\n${subdomainSectionSource}`, /useDomainCardContext/)
  assert.doesNotMatch(`${flatSectionSource}\n${pathgroupSectionSource}\n${subdomainSectionSource}`, /dedupeBadgesClosing\?:|onActiveSuppressedTitleChange\?:|onHoverUrlChange\?:|onLayoutChange\?:/)
  assert.doesNotMatch(domainCardSource, /querySelectorAll/)
  assert.doesNotMatch(`${appSource}\n${appComponentSource}\n${toastSource}`, /vendor\/preact|vendor\/htm/)
  assert.doesNotMatch(sharedTypesSource, /const chrome:\s*any/)
})

test('repo hooks verify changes and reject unsafe commit references', () => {
  assert.ok(existsSync('.githooks/pre-commit'), 'pre-commit hook should be committed for local setup')
  assert.ok(existsSync('.githooks/commit-msg'), 'commit-msg hook should check proposed messages')
  assert.ok(existsSync('.githooks/pre-push'), 'pre-push hook should check outgoing commits')

  const preCommitHook = readFileSync('.githooks/pre-commit', 'utf8')
  const commitMessageHook = readFileSync('.githooks/commit-msg', 'utf8')
  const prePushHook = readFileSync('.githooks/pre-push', 'utf8')
  assert.notEqual(statSync('.githooks/commit-msg').mode & 0o111, 0)
  assert.notEqual(statSync('.githooks/pre-push').mode & 0o111, 0)
  assert.match(preCommitHook, /^#!\/bin\/sh/)
  assert.match(preCommitHook, /pnpm verify/)
  assert.match(commitMessageHook, /check-commit-references\.ts --message-file/)
  assert.match(prePushHook, /check-commit-references\.ts --pre-push/)
})

test('commit reference policy records custom-autolink audit status', () => {
  const policy = JSON.parse(
    readFileSync('.github/commit-reference-policy.json', 'utf8')
  ) as { customAutolinks: unknown[]; customAutolinksAudited: boolean }

  assert.deepEqual(policy.customAutolinks, [])
  assert.equal(policy.customAutolinksAudited, false)
})

test('built extension bundle is packaged locally', () => {
  assert.ok(existsSync('extension/dist/app.js'), 'extension/dist/app.js should be committed build output for unpacked extension loading')
  assert.ok(existsSync('extension/dist/background.js'), 'extension/dist/background.js should be committed service worker output')
  assert.equal(existsSync('extension/dist/app.js.map'), false, 'production build should not ship a sourcemap')
  assert.equal(existsSync('extension/dist/background.js.map'), false, 'production build should not ship a service-worker sourcemap')
  assert.equal(existsSync('extension/dist/chunks'), false, 'dashboard UI should be bundled into one JS entry')
  assert.ok(existsSync('extension/dist/assets/app.css'), 'extension/dist/assets/app.css should be committed stylesheet output')

  const distFiles = readdirSync('extension/dist').sort()
  const assetFiles = readdirSync('extension/dist/assets').sort()
  const assetJsFiles = assetFiles.filter((name) => name.endsWith('.js'))
  const indexHtml = readFileSync('extension/index.html', 'utf8')
  assert.deepEqual(distFiles, ['app.js', 'assets', 'background.js', 'filter-focus-boot.js'])
  assert.ok(assetFiles.includes('app.css'))
  assert.equal(assetJsFiles.length, 8)
  assert.ok(assetJsFiles.some((name) => /^startup-order-debug-heavy-[A-Za-z0-9_-]+\.js$/.test(name)))
  assert.ok(assetJsFiles.some((name) => /^bookmarks-[A-Za-z0-9_-]+\.js$/.test(name)))
  assert.ok(!assetJsFiles.some((name) => /^CardActionsMenuLoaded-[A-Za-z0-9_-]+\.js$/.test(name)))
  assert.ok(assetJsFiles.some((name) => /^HistoryRangeSelect-[A-Za-z0-9_-]+\.js$/.test(name)))
  assert.ok(assetJsFiles.some((name) => /^history-source-[A-Za-z0-9_-]+\.js$/.test(name)))
  assert.ok(assetJsFiles.some((name) => /^mountToast-[A-Za-z0-9_-]+\.js$/.test(name)))
  assert.ok(!assetJsFiles.some((name) => /^PageChipContextMenuLoaded-[A-Za-z0-9_-]+\.js$/.test(name)))
  assert.ok(assetJsFiles.some((name) => /^ReactStore-[A-Za-z0-9_-]+\.js$/.test(name)))
  assert.ok(assetJsFiles.some((name) => /^rolldown-runtime-[A-Za-z0-9_-]+\.js$/.test(name)))
  assert.ok(!assetJsFiles.some((name) => /^TitleSuppressionTokenContextMenuLoaded-[A-Za-z0-9_-]+\.js$/.test(name)))
  assert.ok(assetJsFiles.some((name) => /^getPseudoElementBounds-[A-Za-z0-9_-]+\.js$/.test(name)))
  assert.deepEqual(readdirSync('extension').filter((name) => name.endsWith('.js')), [])
  assert.doesNotMatch(indexHtml, /config\.local\.js/)

  const bundle = readFileSync('extension/dist/app.js', 'utf8')
  const backgroundBundle = readFileSync('extension/dist/background.js', 'utf8')
  const stylesheet = readFileSync('extension/dist/assets/app.css', 'utf8')
  assert.doesNotMatch(bundle, /from\s+['"]https?:\/\//)
  assert.doesNotMatch(backgroundBundle, /from\s+['"]https?:\/\//)
  assert.doesNotMatch(bundle, /vendor\/preact|vendor\/htm/)
  assert.match(bundle, /mission-card/)
  assert.match(stylesheet, /\.dashboard-main/)
  assert.match(stylesheet, /body\{[^}]*font-family:sans-serif/)
  assert.doesNotMatch(stylesheet, /@layer base\{/)
  assert.doesNotMatch(stylesheet, /@layer components\{/)
  assert.doesNotMatch(stylesheet, /@font-face/)
  assert.doesNotMatch(stylesheet, /url\(["']?https?:\/\//)
  assert.doesNotMatch(stylesheet, /tailwindcss\/preflight/)
})
